includes:
- configs/SPICE/solvated_amino_acids/painn/painn-small.yml

trainer: src.distill_trainer.DistillTrainer

dataset:
  train:
    teacher_labels_folder: data/labels/SPICE_labels/mace_off_large_SpiceAminos

loss_functions:
  - energy:
      fn: per_atom_mae
      coefficient: 5
  - forces:
      fn: l2mae
      coefficient: 100
  - teacher_forces:
      fn: l2mae
      coefficient: 0
  - force_jacs:
      fn: l2mae
      coefficient: 400

optim:
  force_jac_sample_size: 1
  print_memory_usage: False
  vectorize_jacs: True
  energy_distill_coeff: 5

