includes:
# update path for base.yml
- /scratch/civil/staff/anair.cstaff/Fine-tuning-UMLFFS/configs/MPMorph/Li/base_wandb.yml

model:
  name: allegro 

optim:
  batch_size: 1
  eval_batch_size: 1
  num_workers: 4
  lr_initial: 0.001
  optimizer: AdamW
  optimizer_params: {"eps": 1.e-7, "weight_decay": 0.000002, "amsgrad": True}
  
  scheduler: ReduceLROnPlateau
  patience: 5
  factor: 0.8
  min_lr: 0.000001  
  max_epochs: 1
  ema_decay: 0.999
  clip_grad_norm: 10
