includes:
# update path for base.yml
- /scratch/civil/staff/anair.cstaff/mlff-distill_stuff/configs/MPMorph/Li/base_wandb.yml

model:
  name: gemnet_t
  num_spherical: 7
  num_radial: 6
  num_blocks: 4 # normal!
  emb_size_atom: 64 #smaller
  emb_size_edge: 64 #smaller
  emb_size_trip: 32 #smaller
  emb_size_rbf: 16
  emb_size_cbf: 16
  emb_size_bil_trip: 64
  num_before_skip: 1
  num_after_skip: 1
  num_concat: 1
  num_atom: 2
  cutoff: 5.0
  max_neighbors: 50
  rbf:
    name: gaussian
  envelope:
    name: polynomial
    exponent: 5
  cbf:
    name: spherical_harmonics
  output_init: HeOrthogonal
  activation: silu
  # update scale_file path
  scale_file: /scratch/civil/staff/anair.cstaff/mlff-distill_stuff/configs/MPMorph/gemnet-dT-scale.json
  extensive: True 
  otf_graph: True
  regress_forces: True
  direct_forces: True # IMPORTANT: change if you want a conservative model (Gemnet-T)

optim:
  batch_size: 1
  eval_batch_size: 1
  num_workers: 4
  lr_initial: 0.001
  optimizer: AdamW
  optimizer_params: {"eps": 1.e-7, "weight_decay": 0.000002, "amsgrad": True}
  
  scheduler: ReduceLROnPlateau
  patience: 5
  factor: 0.8
  min_lr: 0.000001  
  max_epochs: 10
  ema_decay: 0.999
  clip_grad_norm: 10
