includes:
- configs/SPICE/solvated_amino_acids/gemnet-dT-small.yml

model:
  name: src.models.gemnet_baseline.GemNetT
  baseline: True
  use_teacher_node_embeddings: False
  use_teacher_atom_embeddings: True
  teacher_atom_embedding_path: data/labels/atom_embeddings/mace_off_large_atom_embeddings.npy
  emb_size_teacher: 224
  